name: Gamedoora-UI dev deployment

on: 
  workflow_dispatch:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        env:
          NODE_ENV: development
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Create .env
        run: |
          echo VUE_APP_FIREBASE_APIKEY=${{ secrets.VUE_APP_FIREBASE_APIKEY }} >> .env
          echo VUE_APP_FIREBASE_AUTHDOMAIN=${{ secrets.VUE_APP_FIREBASE_AUTHDOMAIN }} >> .env
          echo VUE_APP_FIREBASE_PROJECTID=${{ secrets.VUE_APP_FIREBASE_PROJECTID }} >> .env
          echo VUE_APP_FIREBASE_STORAGEBUCKET=${{ secrets.VUE_APP_FIREBASE_STORAGEBUCKET }} >> .env
          echo VUE_APP_FIREBASE_MESSAGINGSENDERID=${{ secrets.VUE_APP_FIREBASE_MESSAGINGSENDERID }} >> .env
          echo VUE_APP_FIREBASE_APPID=${{ secrets.VUE_APP_FIREBASE_APPID }} >> .env
          echo VUE_APP_FIREBASE_DATABASEURL=${{ secrets.VUE_APP_FIREBASE_DATABASEURL }} >> .env
          cat .env
      - run: npm install 
      - run: export CI=false && npm run lint 
      - run: npm run test:unit  
      - run: npm run build:dev
      - name: Deploy Gamedoora-UI
        if: success()
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with: 
          ACCESS_TOKEN: ${{ secrets.GAMEDOORA_DEV }}
          BRANCH: gh-pages
          FOLDER: dist
