name: Test & Build Gamedoora-UI

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 20.x
      env:
        NODE_ENV: development
      uses: actions/setup-node@v2
      with:
        node-version: 20.x
      
    - name: Install and copy env
      run: |
        npm install
        env | grep "^(NEXT|GAMEDOORA)" | sed 's/\(.*\)=\(.*\)/\1="\2"/g' >> .env

    - name: Run lint
      run: |
        npm run lint

    - name: Run tests
      run: |
        npm test

    - name: Run build
      run: |
        npm run build
        